### ISSUE TITLE
tinc@meshvpn in systemctl 

### ISSUE THREAD

**Issue by PigNatovsky** [chmod666org/scaleway-k8s#20]
In Your configuration, tinc creates only one VPN, so running it with explicit @meshvpn argument isn't necessary. In my case, systemd could not properly interpret tinc@meshvpn. I just start it with `systemctl start tinc` and everything runs well.
Is that only my strange case?

**Comment by Ananasr** [comment]
+1! I also notice that.

**Comment by PigNatovsky** [comment]
This is the answer: 3f6c663a06aac728912c4e47cbc2dc4343a3798c

**Comment by PigNatovsky** [comment]
Ok, next part of investigation: tinc@netname works only, if service is started from /lib/systemd/system/tinc@.service. In our case, tinc is started from /etc/init.d/tinc - this is port of starting script from RHEL. Link added by me in previous comment showing, that systemd service have hook for tinc@netname.service.
