### ISSUE TITLE
Issue with apt-get

### ISSUE THREAD

**Issue by ticruz38** [chmod666org/scaleway-k8s#22]
First of all thanks for the great work.
I follow your blog post and tried to deploy this cluster on Scaleway. But unfortunately, I had a few difficulties.
Trying to fetch package with apt-get on Ubuntu Zesty gave me an error, asking to upgrade to ubuntu 17.10... sadly this image is unavailable on Scaleway yet.
I then deployed a set of machine running Xenial. The node proxy0 could install it's package and run tinyproxy. 
However when proxy1 run apt-get, it passes by proxy0 through a proxy, but the proxy's url is unreachable. The port are indeed open on proxy 0.
Here is what I get when running `netstat -ntlp | grep LISTEN` on proxy0:
```
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3244/sshd
tcp        0      0 192.168.66.1:8888       0.0.0.0:*               LISTEN      20229/tinyproxy
tcp        0      0 0.0.0.0:655             0.0.0.0:*               LISTEN      10424/tincd
tcp6       0      0 :::22                   :::*                    LISTEN      3244/sshd
```
doing curl proxy0IP:8888 return a connexion refused
And here is the message error from proxy1:

> Could not connect to 10.2.107.93:8888 (10.2.107.93). - connect (111: Connection refused)

The Ansible-playbook then fails a few step later when it ensure tinc is started. With the same error on all nodes 
> Could not find the requested service tinc@meshvpn: host

**Comment by chmod666org** [comment]
Hi, can you please show the content of the tinyproxy configuration file. You should have the private ip or the hostname of the second proxy node in it.

**Comment by ticruz38** [comment]
Yes I kept on investing it, I had a proxy config file in etc/apt that gave me the host of proxy0.
I fixed that step by fetching my package manually (without proxying to proxy0),then re-launched ansible, but then I got stuck with ansible at the exact same step when it ensures tinc is started:
> Could not find the requested service tinc@meshvpn: host

I can't reproduce since I destroyed the machines with terraform and moved on to another proxy configuration. However I may give this another try and let you know.

**Comment by allthatnet** [comment]
It should work fine, if you comment out in Ansible plays:

  with_items:
#    - tinc@meshvpn
    - tinc

**Comment by ticruz38** [comment]
I did comment tinc@meshvpn that everywhere, but Ansible was still asking after that. Maybe there is a kind of rollout to do as well I don't know. I'll give it another try

**Comment by andrewmackrodt** [comment]
@ticruz38 the tinyproxy configuration makes it listen on only one interface, in this case it's the tinc interface. You'll need to comment out the line "Listen 192.168.66.1" on proxy0 and reload the service. I'm working on a [PR in my fork](https://github.com/andrewmackrodt/scaleway-k8s/pull/1) which listens on all interfaces for this very reason, i.e. adding a proxy2 server would not work.

**Comment by ticruz38** [comment]
ok @andrewmackrodt, good to hear that someone fixed that issue, I'm closing for now and will try with your fork.
